export const REQUEST_RECIPE_DATA: string = "REQUEST_RECIPE_DATA";
export const REQUEST_RECIPE_SUCCESS: string = "REQUEST_RECIPE_SUCCESS";
export const REQUEST_RECIPE_FAILURE: string = "REQUEST_RECIPE_FAILURE";

export const REQUEST_INGREDIENTS_DATA: string = "REQUEST_INGREDIENTS_DATA";
export const REQUEST_INGREDIENTS_SUCCESS: string = "  REQUEST_INGREDIENTS_SUCCESS";
export const REQUEST_INGREDIENTS_FAILURE: string = "  REQUEST_INGREDIENTS_FAILURE";

export const REQUEST_MARKET_DATA: string = "REQUEST_MARKET_DATA";
export const REQUEST_MARKET_SUCCESS: string = "  REQUEST_MARKET_SUCCESS";
export const REQUEST_MARKET_FAILURE: string = "  REQUEST_MARKET_FAILURE";
